### ISSUE TITLE
bug in RobustFill solve_problems

### ISSUE THREAD

**Issue by mahmoud-safari** [amitz25/PCCoder#2]
Hello, 

We have trained the RobustFill model and noticed that it is not able to solve any problems of any length, for instance the length-one program:

`{"program": "LIST|MAP,+1,0", "examples": [{"inputs": [[-20, 49]], "output": [-19, 50]}, {"inputs": [[-24]], "output": [-23]}, {"inputs": [[-39, 30, -25]], "output": [-38, 31, -24]}, {"inputs": [[-87, 46, 3]], "output": [-86, 47, 4]}, {"inputs": [[-76, -29, -73, -39]], "output": [-75, -28, -72, -38]}]}`

We were wondering if this is the latest version.

**Comment by amitz25** [comment]
Sorry for the late comment, I must've missed the issue.
What you're saying seems very weird.. it definitely worked for me at the time. It's possible that the RobustFill code broke at some point due to refactoring.
I'll try to take a look in the next few days

**Comment by mahmoud-safari** [comment]
Thank you. It seems that the code uses only the statements HEAD (0,) and TAIL (0,). So it can solve problems with solutions HEAD (0,) or TAIL (0,) or those with a trivial solution such as MAP,+1,0|MAP,-1,1 where input = output.

**Comment by amitz25** [comment]
I've tried training a RobustFill model on a new environment with a newly generated dataset and it works perfectly fine for me.
Just for the experiment, I generated a small dataset of length of up to 5 lines with 20k train programs and 500 test programs and trained a RobustFill model on it. It solved 8% of the problems, including non-trival ones.

I've generated the dataset using the following line:
`python -m scripts.gen_programs --num_train=20000 --num_test=500 --train_output_path=train_dataset --test_output_path=test_dataset --max_train_len=5 --test_lengths="5" --num_workers=8`

An example of a solved program:
`{"program": "LIST|LIST|HEAD,1|MAXIMUM,0|TAKE,3,1|DROP,2,4|REVERSE,5", "examples": [{"inputs": [[2, 217, 133, 62, 93, 75, 62, 252, 54, 141, 114, 27, 21, 210, 185, 130, 189], [0, 9, 6, 8, 2, 3, 2, 10, 10, 2, 10, 5]], "output": [5, 10, 2, 10, 10, 2, 3, 2, 8, 6, 9, 0]}, {"inputs": [[135, 221, 158, 152, 174, 107, 183, 81, 24, 105, 105, 198, 246, 205, 166, 97], [1, 0, 0]], "output": [0, 0]}, {"inputs": [[116, 216], [6, 7, 7, 12, 0, 2, 4, 8, 5, 11, 2, 1, 0, 12]], "output": [12, 0, 1, 2, 11, 5, 8, 4]}, {"inputs": [[74, 45, 30, 174, 99, 38, 233, 23, 17, 125, 57, 154, 245, 241, 162, 135, 198], [5, 4, 4, 1, 3, 3, 0]], "output": [0, 3]}, {"inputs": [[12, 57, 106, 71, 248, 101, 204, 121, 16, 95, 202, 2, 128, 221, 146], [11, 1, 9, 1, 0, 3, 10, 1, 8, 2, 7, 10, 0]], "output": [0, 10]}]}`
The solution found is:
`"{'result': 'LIST|LIST|HEAD,1|MAXIMUM,0|DROP,2,1|REVERSE,4', 'num_steps': 1, 'time': 90.21170735359192, 'beam_size': 400, 'width': 48}"`

Please check if you run the code correctly, if the network is training properly and if your PyTorch version is correct (I suggest using 0.4.0).
