### ISSUE TITLE
how to run DeepCoder

### ISSUE THREAD

**Issue by shrivastavadisha** [amitz25/PCCoder#5]
Hey, I wanted to know how to run DeepCoder (https://openreview.net/pdf?id=ByldLrqlx) using this repo. I couldn't find a straightforward way of doing that. I assume there is a simple way though because the PCCoder paper states that the deepcoder baselines are re-implemented here.

**Comment by amitz25** [comment]
You're right, it looks like the DeepCoder reimplementation has not been added to the repo. My mistake.
It's been a long time so sadly I don't have it anymore. If you're interested in running DeepCoder, implementing the model and using the DSL and dataset from this repo should be simple enough.
Alternatively, you can use the re-implementation here: https://github.com/dkamm/deepcoder. From our experience, it works well and this is what we used at the beginning of our research.

**Comment by shrivastavadisha** [comment]
Hey Amit,

Sorry I couldn't find a corresponding email for reaching out to you.
Actually, I am using your PCCoder codebase for my project and building on
top of it. Will it be possible for you to add a licence to your repo so
that it will be easier for me to mention that for my research purposes? The
place I am working/ submitting requires me to specify the license of the
works I have used.

Thanks and Regards,
Disha
